"""add watchstocks table

Revision ID: d3703779b1fb
Revises: 35f07250d494
Create Date: 2020-12-26 10:15:40.610712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3703779b1fb'
down_revision = '35f07250d494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchstocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('current_share_price', sa.Integer(), nullable=True),
    sa.Column('current_share_price_date', sa.DateTime(), nullable=True),
    sa.Column('fiftytwo_week_low', sa.Integer(), nullable=True),
    sa.Column('fiftytwo_week_high', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.String(), nullable=True),
    sa.Column('dividend_per_share', sa.Integer(), nullable=True),
    sa.Column('pe_ratio', sa.Integer(), nullable=True),
    sa.Column('peg_ratio', sa.Integer(), nullable=True),
    sa.Column('profit_margin', sa.Integer(), nullable=True),
    sa.Column('beta', sa.Integer(), nullable=True),
    sa.Column('stock_data_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchstocks')
    # ### end Alembic commands ###
