"""add price to book ratio in watchstocks table

Revision ID: ff3b73808d50
Revises: d3703779b1fb
Create Date: 2020-12-29 09:35:45.034376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3b73808d50'
down_revision = 'd3703779b1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchstocks', sa.Column('price_to_book_ratio', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchstocks', 'price_to_book_ratio')
    # ### end Alembic commands ###
